name: Dev-Testing

run-name: ${{ github.actor }} is pushing a change to the code
on:
  push:
    branches:
      - Dev
jobs:
  test-remove-user-script:
    runs-on: windows-latest
    environment: Dev
    steps:
    - name: check out Windows-Scripts repository
      uses: actions/checkout@v3
    - name: Set up the machine for \Remove-FullUserAccountDetails.tests.ps1 Unit tests
      shell: pwsh
      run: |
         $Password = Convertto-SecureString "password123!ABC" -asplaintext -force
         $Username = "Test_User"
         New-LocalUser -Name $Username -Password $Password
    - name: GHA Tests
      run: |
         $ProfileListRegKey = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\*"
         Get-Itemproperty $ProfileListRegKey -name ProfileImagePath | `
          Where-Object -property ProfileImagePath -Like ("*" + $Username)
    - name: Run remove user tests
      run: Invoke-Pester -Path .\Remove-FullUserAccountDetails.tests.ps1 -passthru