name: Dev-Testing

run-name: ${{ github.actor }} is pushing a change to the code
on:
  push:
    branches:
      - Dev
jobs:
  test-remove-user-script:
    runs-on: windows-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v3
    - run: |
         $Password = Convertto-SecureString "password123!ABC" -asplaintext -force
         $Username = "Test_User"
         New-LocalUser -Name $Username -Password $Password
         get-localuser
    - name: Run remove user tests
      shell: pwsh
      run: Invoke-Pester -Path .\Remove-FullUserAccountDetails.tests.ps1 -passthru