name: Dev-Testing

run-name: ${{ github.actor }} is pushing a change to the code
on:
  push:
    branches:
      - Dev
jobs:
  test-remove-user-script:
    runs-on: windows-latest
    environment: Dev
    steps:
    - name: check out Windows-Scripts repository
      uses: actions/checkout@v3
    - name: Set up the machine for \Remove-FullUserAccountDetails.tests.ps1 Unit tests
      shell: pwsh
      run: |
         $Password = Convertto-SecureString "password123!ABC" -asplaintext -force
         $Username = "Test_User"
         New-LocalUser -Name $Username -Password $Password
    - name: GHA Tests
      run: |
         $Username = "Test_User"
         $ProfileListRegKey = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList"
         $UserRegKeyName = "1235465test" 
         New-Item -Path $ProfileListRegKey -Name ($UserRegKeyName + $UserRegKeyName + "\" + $Username)
         New-itemproperty -Path ($ProfileListRegKey + $UserRegKeyName + "\" + $Username) -Name ProfileImagePath -Value "C:\Users\$Username"
    - name: Run remove user tests
      run: Invoke-Pester -Path .\Remove-FullUserAccountDetails.tests.ps1 -passthru