name: Test-Windows-Scripts

run-name: ${{ github.actor }} is pushing a change to the code
on: 
  push:
    branches: 
      - Test
jobs:
  build-windows-pc:
    runs-on: windows-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v3
    - run: $PSVersionTable
